// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenPass is an autogenerated mock type for the GenPass type
type GenPass struct {
	mock.Mock
}

// GeneratePassword provides a mock function with no fields
func (_m *GenPass) GeneratePassword() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GeneratePassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewGenPass creates a new instance of GenPass. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenPass(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenPass {
	mock := &GenPass{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
