// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KeyGenerator is an autogenerated mock type for the KeyGenerator type
type KeyGenerator struct {
	mock.Mock
}

// GenerateKey provides a mock function with given fields: length
func (_m *KeyGenerator) GenerateKey(length int) string {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GenerateRandomString provides a mock function with given fields: length
func (_m *KeyGenerator) GenerateRandomString(length int) string {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewKeyGenerator creates a new instance of KeyGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyGenerator {
	mock := &KeyGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
